### PR TITLE
aom: Add vmaf tune support

### PR DESCRIPTION
**Pull request by 1480c1**
Tested and everything compiled fine

### CODE REVIEW

**Comment by wiiaboo** [comment]
Isn't this only used by aomenc? Or also by libaom?

**Comment by 1480c1** [comment]
Only aomenc I believe

**Comment by Selur** [comment]
aomenc offers: `--tune=vmaf` as option, but when that option is used one gets:
```
Failed to control codec: Invalid parameter
    This error may be related to the wrong configuration options: try to set -DCONFIG_TUNE_VMAF=1 at the time CMake is run.
```
-> would be nice it tune vmaf would be enabled in cmake

**Comment by moisespr123** [comment]
The commit was reverted.

**Comment by Selur** [comment]
any news on this?

**Pull request merged**
