### PR TITLE
SVT-VP9: Add SVT-VP9

### LINKED ISSUE #1094: (low-prio suggestion) OpenVisualCloud SVT-VP9/AV1
New high performance Scalable Video VP9 encoder (with rather high CPU requirements): [OpenVisualCloud SVT-VP9](https://github.com/OpenVisualCloud/SVT-VP9)

> The Scalable Video Technology for VP9 Encoder (SVT-VP9 Encoder) is a VP9-compliant encoder library core. The SVT-VP9 Encoder development is a work-in-progress targeting performance levels applicable to both VOD and Live encoding/transcoding video applications.

Also mentioned at [FRESHports](https://www.freshports.org/multimedia/svt-vp9/) and in its [SVNweb](https://svnweb.freebsd.org/ports/head/multimedia/svt-vp9/) so I guess there are efforts to bring it into ffmpeg. May be postponed until there is official support.

Also, a similar AV1 project: [OpenVisualCloud SVT-AV1](https://github.com/OpenVisualCloud/SVT-AV1)

### PR DESCRIPTION
**Pull request by 1480c1**
Closes #1094

I haven't added the ffmpeg plugin since there already seems to be some issues with svt-{av1,hevc} ffmpeg etc

### CODE REVIEW

**Comment by 1480c1** [comment]
Sure, I'll do it later for the SVT encoders

**Comment by wiiaboo** [comment]
Built it manually, exe ran, seems fine. Are these SVT encoders any better than google's?

**Comment by 1480c1** [comment]
Supposedly at least for SVT-AV1: https://medium.com/@ewoutterhoeven/av1-is-ready-for-prime-time-svt-av1-beats-x265-and-libvpx-in-quality-bitrate-and-speed-31c1960703db

AKAIK, they're putting more focus on the av1 encoder since av1 is very new and they're trying to be the first in terms of distribution outside of youtube and vimeo. As such, the SVT-HEVC and SVT-VP9 aren't as maintained as well.

They're supposedly faster than google's for streaming, but maybe not so for quality

**Comment by wiiaboo** [comment]
Do the comparisons include BBB's company's encoder too? (TwoSomething?)

**Comment by wiiaboo** [comment]
They don't, but Eve-AV1 does have comparisons with SVT-AV1 and libaom and rav1e. No idea on how old the comparisons are there, though.

**Comment by nistvan86** [comment]
Any chance of adding the plugin for SVT-VP9 as well? In my recent ffmpeg build SVT-AV1 and SVT-HEVC support is already present, but SVT-VP9 is missing, although the separate encoder was built.

It seems there are some plugin instructions to deal with combined usage: https://github.com/OpenVisualCloud/SVT-VP9/tree/master/ffmpeg_plugin
I don't know if you have already tried this.

**Comment by 1480c1** [comment]
I can add it soon, however one issue is that mkv/webm support is still a bit broken, so you would only be able to encode to ivf right now

**Comment by 1480c1** [comment]
https://github.com/OpenVisualCloud/SVT-VP9/issues/74

**Comment by nistvan86** [comment]
So at the moment this is blocked by the Windows build bug found here: https://github.com/OpenVisualCloud/SVT-VP9/pull/79#issuecomment-577300670 right?

**Comment by 1480c1** [comment]
Yes

**Comment by nistvan86** [comment]
Lost tracking this issue for the past months.
Is this the latest change on the ffmpeg plugin? https://github.com/OpenVisualCloud/SVT-VP9/pull/92
Is there anything still blocking the integration?
I'm not in any hurry, just curious.

**Comment by 1480c1** [comment]
I can't remember any exact reason, I can retry again

**Pull request merged**
