### PR TITLE
CFLAGS: Add stack-protector-strong

### LINKED ISSUE #1450: [mingw32] libwebp fails to build with undef to __memcpy_chk
Running git clone for libwebp...
┌ libwebp git  ........................................ [Recently updated]
├ Running autoreconf...
├ Running configure...
├ Running make...
Likely error (tail of the failed operation logfile):
D:/media-ab_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-ab_suite/build/libwebp-git/build-32bit/src/.libs/libwebp.a(libwebpdspdecode_sse2_la-upsampling_sse2.o):upsampling_sse2.c:(.text+0xc53): undefined reference to `__memcpy_chk'
D:/media-ab_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-ab_suite/build/libwebp-git/build-32bit/src/.libs/libwebp.a(libwebpdspdecode_sse2_la-upsampling_sse2.o):upsampling_sse2.c:(.text+0xc72): undefined reference to `__memcpy_chk'
D:/media-ab_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-ab_suite/build/libwebp-git/build-32bit/src/.libs/libwebp.a(libwebpdspdecode_sse2_la-upsampling_sse2.o):upsampling_sse2.c:(.text+0xcf0): undefined reference to `__memcpy_chk'
D:/media-ab_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-ab_suite/build/libwebp-git/build-32bit/src/.libs/libwebp.a(libwebpdspdecode_sse2_la-upsampling_sse2.o):upsampling_sse2.c:(.text+0xd0b): undefined reference to `__memcpy_chk'
D:/media-ab_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-ab_suite/build/libwebp-git/build-32bit/src/.libs/libwebp.a(libwebpdspdecode_sse2_la-upsampling_sse2.o):upsampling_sse2.c:(.text+0x146a): undefined reference to `__memcpy_chk'
D:/media-ab_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-ab_suite/build/libwebp-git/build-32bit/src/.libs/libwebp.a(libwebpdspdecode_sse2_la-upsampling_sse2.o):upsampling_sse2.c:(.text+0x1493): more undefined references to `__memcpy_chk' follow
collect2.exe: error: ld returned 1 exit status
make[1]: *** [Makefile:441: webp_quality.exe] Error 1
make[1]: Leaving directory '/build/libwebp-git/build-32bit/extras'
make: *** [Makefile:420: all-recursive] Error 1
make failed. Check D:/media-ab_suite/build/libwebp-git/build-32bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/z3Rv.zip
Copy and paste [logs.zip](https://0x0.st/z3Rv.zip) in the GitHub issue.

### LINKED ISSUE #1463: jq build error
Compile failure. jq-git
https://0x0.st/zgWh.zip

```
14:50:39
        Starting 64bit compilation of all tools
Imported default FFmpeg options from .bat
License: nonfree
Imported default mpv options from .bat
14:50:46
        Starting 64bit compilation of global tools
14:50:46 oniguruma git  ................................. [Already built]
14:50:47   Running git update for jq...
14:50:47 ┌ jq git  ................................... [Recently updated]
14:50:47 ├ Running autoreconf...
Likely error (tail of the failed operation logfile):
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
autoreconf -fiv
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I config/m4
autoreconf: aclocal terminated by signal: 2
autom4te: /usr/bin/m4 terminated by signal: 2
autoreconf failed. Check C:/MAB/build/jq-git/ab-suite.autoreconf.log
This is required for other packages, so this script will exit.
14:50:51   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/zg4X.zip
Copy and paste [logs.zip](https://0x0.st/zg4X.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

```

### PR DESCRIPTION
**Pull request by 1480c1**
Related to #1464
Fixes #1463
Fixes #1450

Also re-set fortify source to 2

@Helenerineium can you check to make sure this is fine?

### CODE REVIEW

**Comment by wiiaboo** [comment]
I'm not getting broken builds even without this.
I'm using custom_build_options with `export CFLAGS="-mthreads -march=native -O3 -pipe"` though. That shouldn't be affecting anything.

**Comment by 1480c1** [comment]
I don't either all of the time, but I think it maybe one of those not easily reproducible things (I sometimes get it on my laptop and desktop, sometime not, I can't find a specific way to force a reproduction)

**Comment by 1480c1** [comment]
Blocked by libtiff right now

**Comment by wiiaboo** [comment]
No one with issues has yet confirmed this fixes anything, so I can't approve it yet.

**Pull request closed without merging**
