### PR TITLE
update python and vapoursynth

### PR DESCRIPTION
**Pull request by woot000**
it builds fine and seems to work in ffmpeg

### CODE REVIEW

**Comment by 1480c1** [comment]
Do you happen to have Windows 7 machine to test compilation and also running it?

Python 3.9 officially dropped support for Win7 and has moved to using some APIs from 8.1 and on, but msys2 has some patches, so their python still works with win7, but I don't know if vapoursynth's stuff still works with win7

**Comment by woot000** [comment]
unfortunately not
i'd test it on a virtual machine but vmware has been acting buggy for me on my windows 11 machine so i wouldn't be able to say for sure that vapoursynth would work

**Comment by 1480c1** [comment]
🤷

**Comment by 1480c1** [comment]
Thanks for the help

**Pull request merged**
