### PR TITLE
Bat: Add low prio option

### PR DESCRIPTION
**Pull request by 1480c1**
Might help with people who want to compile in the background, we could add more priority options too

### CODE REVIEW

**Comment by wiiaboo** [comment]
Does this actually do anything? (honestly curious)

**Comment by 1480c1** [comment]
It sets mintty and bash and spawned process to low priority, so at least i can play games while a compile is running in the background without it freezing or lagging my game

**Comment by wiiaboo** [comment]
Couldn't you just use lower cpuCount?

**Comment by wiiaboo** [comment]
I'd even agree to always run the suite on low priority as a base, since if you're not doing anything else, it'll probably compile just as fast.

**Comment by 1480c1** [comment]
Yeah, the main reason to have this set to on would be so during lull times the compile will run at full speed, but can be backgrounded if there's something more pressing.

Should i set this to default?

**Comment by wiiaboo** [comment]
Sure.

**Pull request merged**
