### PR TITLE
x265: Changed x265 hg source to x265 git.

### LINKED ISSUE #1548: x265 will migrate to Git
Until June 2020, bitbucket will remove Mercurial support.

The new Git repo URL will be: https://bitbucket.org/multicoreware/x265_git/

### PR DESCRIPTION
**Pull request by moisespr123**
Closes #1548

### CODE REVIEW

**Comment by 1480c1** [comment]
Although I personally am fine, I'm a bit concerned about the vcs change

**Comment by moisespr123** [comment]
I don't see the x264-hg folder. Just x264-git.

image

**Comment by 1480c1** [comment]
I mean from prior runs

**Comment by 1480c1** [comment]
I don't think it would break anything since we don't particularly have anything relying on x265 being mercurial

**Comment by moisespr123** [comment]
I ran it and everything built fine. No errors occurred during the run.

**Comment by 1480c1** [comment]
Okay then

**Pull request merged**
