### PR TITLE
SVT-AV1: Apply 717 patch if pr is still open and mergeable

### PR DESCRIPTION
**Pull request by 1480c1**
Temp fix for #1441 to apply the pr while it's open and mergeable since it seems it may take some time for upstream to merge

### CODE REVIEW

**Comment by 1480c1** [comment]
Testing if built jq works atm, if not, going to check jq

**Comment by wiiaboo** [comment]
We could always install jq, whether or not we build it, to not get dependent on non-broken builds.
It'll be needed for future features too.

**Comment by 1480c1** [comment]
Seems to work fine for now

**Comment by wiiaboo** [comment]
Works fine because you have jq built, but it'll break for people who don't.

**Comment by 1480c1** [comment]
Need to add pacman_install jq if not jq

**Comment by wiiaboo** [comment]
Just add jq to mingwpackages in the .bat.

**Comment by 1480c1** [comment]
> Just add jq to mingwpackages in the .bat.

done

**Comment by 1480c1** [comment]
Should we stop building jq and use msys2 provided one?

**Comment by wiiaboo** [comment]
No, I want a static one for myself.

**Comment by wiiaboo** [comment]
The libs don't need to be installed, now that I see it. Only the .exe.

**Pull request merged**
