### PR TITLE
libxml2: Compile our own

### PR DESCRIPTION
**Pull request by 1480c1**
Fixes https://github.com/m-ab-s/media-autobuild_suite/issues/1479 maybe

It seems most of the patches applied by msys2 is mainly just to fix warnings with the exception of the one that adds pathtools stuff.

### CODE REVIEW

**Comment by wiiaboo** [comment]
Haven't tested it yet, but make sure there's no tools being built. We only need the lib itself.

**Comment by 1480c1** [comment]
Since they didn't seem to have an option to not build executables, I just added a step that runs their uninstall target with just deletes the executables after running the install

**Comment by wiiaboo** [comment]
I usually patch the Makefile.am to not compile the binaries as well, to not waste time on stuff we don't need.

**Comment by 1480c1** [comment]
Done

**Pull request merged**
