### PR TITLE
vmaf: Use out-of-source cmake instead of meson

### LINKED ISSUE #1466: Building of vmaf not working
```
12:24:09   Running git clone for vmaf...
12:24:29 ┌ vmaf git  ................................. [Recently updated]
12:24:29 ├ Running clean...
12:24:29 ├ Running make...
Likely error (tail of the failed operation logfile):
ninja: Entering directory `.'
[1/2] g++ @tools/vmafossexec.exe.rsp
FAILED: tools/vmafossexec.exe
g++ @tools/vmafossexec.exe.rsp
C:/Development/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Development/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/libgcc_eh.a(unwind-seh.o):(.text+0x3d0): multiple definition of `_Unwind_Resume'; src/libvmaf.dll.a(d000018.o):(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
[2/2] "C:/Development/MABS/msys64/mingw64/bin/meson" "--internal" "vcstagger" "../include/vcs_version.h.in" "include/vcs_version.h" "1.3.16" "C:/Development/MABS/build/vmaf-git/libvmaf/include" "@VCS_TAG@" "(.*)" "C:/Development/MABS/msys64/usr/bin/git.EXE" "--git-dir" "C:/Development/MABS/build/vmaf-git/libvmaf/../.git" "describe" "--tags" "--long" "--match" "?.*.*" "--always"
fatal: Not a valid object name .ninja_log
ninja: build stopped: subcommand failed.
make: *** [Makefile:3: all] Error 1
make failed. Check C:/Development/MABS/build/vmaf-git/ab-suite.make.log
This is required for other packages, so this script will exit.
12:24:38   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/zg03.zip
Copy and paste [logs.zip](https://0x0.st/zg03.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```

### PR DESCRIPTION
**Pull request by 1480c1**
Fixes #1466

vmaf already has a meson build system so I'll just update the patch as they change their system. In the future, I might change it to a gist, but if it's a branch, if someone else wants to pick it up, they can fork it.

### CODE REVIEW

**Comment by 1480c1** [comment]
I just realized this is pull #1480

**Comment by ImportTaste** [comment]
Happy birthday!

**Comment by wiiaboo** [comment]
Aren't they moving to meson-only? Or are they going to mantain both cmake and meson?

**Comment by 1480c1** [comment]
They are meson only with the exception of a third_party libsvm. I did try to submit a pr for [cmake](https://github.com/Netflix/vmaf/pull/378), but they replaced that PR with a [meson](https://github.com/Netflix/vmaf/pull/384) buildsystem

This adds a patch for an `out-of-source` CMakeLists.txt that I will be maintaining for now with parity with their meson system until I can actually find out why their `libvmaf.dll.a` has a conflicting `_Unwind_Resume` from `libgcc_eh.a` or if they seem willing to have two build systems

**Pull request merged**
