### PR TITLE
ffmpeg: Add --allow-multiple-definition to ffmpeg

### LINKED ISSUE #1479: [mingw64] FFmpeg multiple definition of pathtools symbol
``` bash
23:56:39   Running git clone for ffmpeg...
23:58:33 ┌ ffmpeg git  ............................... [Recently updated]
23:58:33 ├ Until SVT-AV1 issues a fix, libsvtav1 must be disabled while libsvthevc is enabled....
23:58:33 ├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
patch unexpectedly ends in middle of line
23:58:43 ├ Compiling static FFmpeg...
23:58:47 ├ Running configure...
00:06:00 ├ Running pre make from vmaf_extra.sh...
00:06:02 ├ Running make...
Likely error (tail of the failed operation logfile):
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mingw/msys64/mingw64/lib/libxml2.a(pathtools.o):(.text+0x6f0): multiple definition of `get_executable_path'; C:/mingw/msys64/mingw64/lib/libcrypto.a(pathtools.o):(.text+0x7e0): first defined here
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mingw/msys64/mingw64/lib/libxml2.a(pathtools.o):(.text+0x7c0): multiple definition of `strip_n_prefix_folders'; C:/mingw/msys64/mingw64/lib/libcrypto.a(pathtools.o):(.text+0x8b0): first defined here
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mingw/msys64/mingw64/lib/libxml2.a(pathtools.o):(.text+0x820): multiple definition of `strip_n_suffix_folders'; C:/mingw/msys64/mingw64/lib/libcrypto.a(pathtools.o):(.text+0x910): first defined here
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mingw/msys64/mingw64/lib/libxml2.a(pathtools.o):(.text+0x870): multiple definition of `split_path_list'; C:/mingw/msys64/mingw64/lib/libcrypto.a(pathtools.o):(.text+0x960): first defined here
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mingw/msys64/mingw64/lib/libxml2.a(pathtools.o):(.text+0x890): multiple definition of `get_relocated_path_list'; C:/mingw/msys64/mingw64/lib/libcrypto.a(pathtools.o):(.text+0x980): first defined here
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mingw/local64/lib/libcodec2.a(c2wideband.c.o): in function `mean':
C:\mingw\build\codec2-0.8-svn\build-64bit/../src/c2wideband.c:339: multiple definition of `mean'; C:/mingw/local64/lib/libvidstab.a(transformtype.c.o):transformtype.c:(.text+0xc80): first defined here
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mingw/local64/lib/libxvidcore.a(idct.obj): warning: common of `idct' overridden by definition from C:/mingw/local64/lib/libcodec2.a(dct2.c.o)
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:111: ffmpeg_g.exe] Error 1
make failed. Check C:/mingw/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
00:24:01   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/z6Zc.zip
Copy and paste [logs.zip](https://0x0.st/z6Zc.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```

[logs.zip](https://0x0.st/z6Zc.zip)
[ab-suite.make.log](https://github.com/m-ab-s/media-autobuild_suite/files/3852387/ab-suite.make.log)

### PR DESCRIPTION
**Pull request by 1480c1**
Fixes #1479

### CODE REVIEW

**Comment by wiiaboo** [comment]
Don't always add it. Only for specific combinations of libs which can't be patched.
We don't want to mask potential issues.

**Comment by wiiaboo** [comment]
Adding that flag will prevent one of the multiple definitions from being available. They're not always the same exact code.

**Comment by wiiaboo** [comment]
You can place it next to the existing libssh check on the start of the ffmpeg code branch.
Then place an array or something with comma-separated combinations of libs which can't be patched to rename the conflicting definitions.

**Comment by wiiaboo** [comment]
[Here](https://github.com/m-ab-s/media-autobuild_suite/blob/master/build/media-suite_compile.sh#L1737-L1742)

**Comment by wiiaboo** [comment]
The criteria for combinations to be there is:
1. they're not built by the suite, so they can't be patched
2. they're built by the suite, but we can't patch them or upstream refuses to fix the issue

If we build and can patch them to resolve the conflicts (like with codec2), they should not be in these combinations.

**Comment by 1480c1** [comment]
Something like
```bash
ffmpeg_conflicting_def_libs=("libxml2 openssl")
...
for conflicting_libs in "${ffmpeg_conflicting_def_libs[@]}"; do
    # shellcheck disable=SC2086
    if enabled_all $conflicting_libs; then
        do_addOption "--extra-ldflags=-Wl,--allow-multiple-definition"
    fi
done
```
?

**Comment by wiiaboo** [comment]
I don't see any conflicts between libxml2 and openssl btw, I've been building them together since FFmpeg first started using libxml2. Where is the issue from this?

But yeah, something like that.

**Comment by wiiaboo** [comment]
Usually the issue is using libressl in some things rather than openssl, and then libressl is missing some symbols from OpenSSL, usually not vice-versa.

**Comment by wiiaboo** [comment]
I don't remember why I initially added libressl, but if it keeps being outpaced by openssl, we might as well drop it.

**Comment by 1480c1** [comment]
> I don't see any conflicts between libxml2 and openssl btw, I've been building them together since FFmpeg first started using libxml2. Where is the issue from this?

https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-openssl/openssl-1.1.1-relocation.patch
https://github.com/msys2/MINGW-packages/blob/5dc2b719903e5520cce991e2d69bb8b666e1f147/mingw-w64-libxml2/0026-mingw-relocate.patch
Since we are using those two packages from msys2, they are using patches that add in functions to help resolve paths, but they do not have different names so they will conflict. I'm not entirely sure why it only popped up recently

**Comment by wiiaboo** [comment]
Why am I not getting any issues from it then? Even disregarding my custom_options which just adds `-mtune=native -O3` to CFLAGS, ffmpeg is building fine with openssl and libxml2.

**Comment by 1480c1** [comment]
I'm not entirely sure either, I've done multiple clean builds on master after deleting local* and all of the folders under build along with msys2, but I'm still able to reproduce the multiple definitions

**Comment by wiiaboo** [comment]
```bash
> grep sanitise_path /mingw64/lib/*.a
Binary file /mingw64/lib/libcrypto.a matches
Binary file /mingw64/lib/libcurl.a matches
Binary file /mingw64/lib/libxml2.a matches
```

Yep, pathtools symbols are there.

**Comment by 1480c1** [comment]
Right now working on a gitlab runner to try to see if I can setup a way to test these commits easily

**Comment by wiiaboo** [comment]
What options are you using, btw?

I have only what I need personally:
```
#--enable-bzlib
#--enable-cuda
#--enable-cuvid
#--enable-d3d11va
#--enable-dxva2
#--enable-iconv
#--enable-lzma
#--enable-nvenc
#--enable-zlib
#--enable-ffnvcodec
#--enable-nvdec

--disable-amf
--disable-sdl2
--disable-debug

--enable-libdav1d
--enable-libwebp
--enable-libxml2
--enable-libzimg
--enable-gpl
--enable-openssl
--enable-version3

--disable-postproc
--disable-podpages
--disable-txtpages
--disable-htmlpages
--disable-demuxer=asf
```

**Comment by 1480c1** [comment]
I've had it set to all for now since I'm testing to make sure none of the packages fail with my commits


```none
[compiler list]
msys2Arch=2
arch=1
license2=1
standalone=1
vpx2=1
aom=1
rav1e=1
dav1d=1
x2643=4
x2652=1
other265=1
svthevc=1
xvc=1
vvc=1
svtav1=1
svtvp9=1
flac=1
fdkaac=1
faac=1
mediainfo=1
soxB=1
ffmpegB2=1
ffmpegUpdate=1
ffmpegChoice=4
mp4box=1
rtmpdump=1
mplayer2=1
mpv=1
bmx=1
curl=1
ffmbc=1
cyanrip2=1
redshift=1
ripgrep=1
jq=1
jo=1
dssim=1
avs2=1
cores=8
deleteSource=1
strip=1
pack=2
logging=1
updateSuite=1
timeStamp=1
ccache=1
noMintty=1
```

**Comment by wiiaboo** [comment]
Testing with mplayer and ffmbc is pointless as they're mostly dead and no one should be using them.

ffmbc's author has been comitting stuff to FFmpeg.

**Comment by 1480c1** [comment]
Yeah, I did notice Baptiste a couple of times in ffnpeg-dev, but just to make sure that none of the changes affect the archaic code in those sections, I have then enabled.

Ideally if nobody complains, we would be able to remove them

**Comment by wiiaboo** [comment]
Nah, some people still compile them, or else I'd've removed them years ago.

**Comment by 1480c1** [comment]
```
D:/media-autobuild_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-autobuild_suite/msys64/mingw32/lib/libcrypto.a(rc4-586.o) and D:/media-autobuild_suite/msys64/mingw32/lib/libcrypto.a(x86-mont.o): warning: multiple common of `OPENSSL_ia32cap_P'
D:/media-autobuild_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-autobuild_suite/msys64/mingw32/lib/libcrypto.a(x86cpuid.o) and D:/media-autobuild_suite/msys64/mingw32/lib/libcrypto.a(x86-mont.o): warning: multiple common of `OPENSSL_ia32cap_P'
D:/media-autobuild_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-autobuild_suite/msys64/mingw32/lib/libcrypto.a(aesni-x86.o) and D:/media-autobuild_suite/msys64/mingw32/lib/libcrypto.a(x86-mont.o): warning: multiple common of `OPENSSL_ia32cap_P'
D:/media-autobuild_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-autobuild_suite/msys64/mingw32/lib/libcrypto.a(bn-586.o) and D:/media-autobuild_suite/msys64/mingw32/lib/libcrypto.a(x86-mont.o): warning: multiple common of `OPENSSL_ia32cap_P'
D:/media-autobuild_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-autobuild_suite/msys64/mingw32/lib/libcrypto.a(chacha-x86.o) and D:/media-autobuild_suite/msys64/mingw32/lib/libcrypto.a(x86-mont.o): warning: multiple common of `OPENSSL_ia32cap_P'
D:/media-autobuild_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-autobuild_suite/msys64/mingw32/lib/libcrypto.a(ecp_nistz256-x86.o) and D:/media-autobuild_suite/msys64/mingw32/lib/libcrypto.a(x86-mont.o): warning: multiple common of `OPENSSL_ia32cap_P'
D:/media-autobuild_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-autobuild_suite/msys64/mingw32/lib/libcrypto.a(poly1305-x86.o) and D:/media-autobuild_suite/msys64/mingw32/lib/libcrypto.a(x86-mont.o): warning: multiple common of `OPENSSL_ia32cap_P'
D:/media-autobuild_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-autobuild_suite/msys64/mingw32/lib/libcrypto.a(sha1-586.o) and D:/media-autobuild_suite/msys64/mingw32/lib/libcrypto.a(x86-mont.o): warning: multiple common of `OPENSSL_ia32cap_P'
D:/media-autobuild_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-autobuild_suite/msys64/mingw32/lib/libcrypto.a(sha256-586.o) and D:/media-autobuild_suite/msys64/mingw32/lib/libcrypto.a(x86-mont.o): warning: multiple common of `OPENSSL_ia32cap_P'
D:/media-autobuild_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-autobuild_suite/msys64/mingw32/lib/libcrypto.a(sha512-586.o) and D:/media-autobuild_suite/msys64/mingw32/lib/libcrypto.a(x86-mont.o): warning: multiple common of `OPENSSL_ia32cap_P'
D:/media-autobuild_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-autobuild_suite/msys64/mingw32/lib/libcrypto.a(x86-gf2m.o) and D:/media-autobuild_suite/msys64/mingw32/lib/libcrypto.a(x86-mont.o): warning: multiple common of `OPENSSL_ia32cap_P'
D:/media-autobuild_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-autobuild_suite/msys64/mingw32/lib/libxml2.a(pathtools.o):(.text+0x100): multiple definition of `malloc_copy_string'; D:/media-autobuild_suite/msys64/mingw32/lib/libcrypto.a(pathtools.o):(.text+0x100): first defined here
D:/media-autobuild_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-autobuild_suite/msys64/mingw32/lib/libxml2.a(pathtools.o):(.text+0x150): multiple definition of `sanitise_path'; D:/media-autobuild_suite/msys64/mingw32/lib/libcrypto.a(pathtools.o):(.text+0x150): first defined here
D:/media-autobuild_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-autobuild_suite/msys64/mingw32/lib/libxml2.a(pathtools.o):(.text+0x1d0): multiple definition of `simplify_path'; D:/media-autobuild_suite/msys64/mingw32/lib/libcrypto.a(pathtools.o):(.text+0x1d0): first defined here
D:/media-autobuild_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-autobuild_suite/msys64/mingw32/lib/libxml2.a(pathtools.o):(.text+0x450): multiple definition of `get_relative_path'; D:/media-autobuild_suite/msys64/mingw32/lib/libcrypto.a(pathtools.o):(.text+0x4d0): first defined here
D:/media-autobuild_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-autobuild_suite/msys64/mingw32/lib/libxml2.a(pathtools.o):(.text+0x730): multiple definition of `get_relocated_path'; D:/media-autobuild_suite/msys64/mingw32/lib/libcrypto.a(pathtools.o):(.text+0x810): first defined here
D:/media-autobuild_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-autobuild_suite/msys64/mingw32/lib/libxml2.a(pathtools.o):(.text+0x780): multiple definition of `get_executable_path'; D:/media-autobuild_suite/msys64/mingw32/lib/libcrypto.a(pathtools.o):(.text+0x860): first defined here
D:/media-autobuild_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-autobuild_suite/msys64/mingw32/lib/libxml2.a(pathtools.o):(.text+0x850): multiple definition of `strip_n_prefix_folders'; D:/media-autobuild_suite/msys64/mingw32/lib/libcrypto.a(pathtools.o):(.text+0x950): first defined here
D:/media-autobuild_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-autobuild_suite/msys64/mingw32/lib/libxml2.a(pathtools.o):(.text+0x8b0): multiple definition of `strip_n_suffix_folders'; D:/media-autobuild_suite/msys64/mingw32/lib/libcrypto.a(pathtools.o):(.text+0x9b0): first defined here
D:/media-autobuild_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-autobuild_suite/msys64/mingw32/lib/libxml2.a(pathtools.o):(.text+0x900): multiple definition of `split_path_list'; D:/media-autobuild_suite/msys64/mingw32/lib/libcrypto.a(pathtools.o):(.text+0xa00): first defined here
D:/media-autobuild_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-autobuild_suite/msys64/mingw32/lib/libxml2.a(pathtools.o):(.text+0x930): multiple definition of `get_relocated_path_list'; D:/media-autobuild_suite/msys64/mingw32/lib/libcrypto.a(pathtools.o):(.text+0xa30): first defined here
D:/media-autobuild_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-autobuild_suite/local32/lib/librav1e.a(compiler_builtins-7e358676639674ac.compiler_builtins.ci8h7165-cgu.0.rcgu.o): in function `_divmoddi4':
C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\compiler_builtins-0.1.18\src/macros.rs:253: multiple definition of `__divmoddi4'; D:/media-autobuild_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/libgcc.a(_divmoddi4.o):(.text+0x0): first defined here
D:/media-autobuild_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-autobuild_suite/local32/lib/librav1e.a(compiler_builtins-7e358676639674ac.compiler_builtins.ci8h7165-cgu.0.rcgu.o): in function `_udivmoddi4':
C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\compiler_builtins-0.1.18\src/macros.rs:253: multiple definition of `__udivmoddi4'; D:/media-autobuild_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/libgcc.a(_udivmoddi4.o):(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:111: ffplay_g.exe] Error 1
```
Openssl seems to have issues within itself too

**Comment by wiiaboo** [comment]
OK, I could finally reproduce it, but only in the shared build, and with a fresh ab installation and with full options.
There might some other thing causing this. I'm up for leaving this to the weekend so we can bisect which crappy option causes this.

**Comment by 1480c1** [comment]
Sure, I'm going to try to work on a gitlab-runner for mabs

**Comment by 1480c1** [comment]
Closing since it's now unecessary

**Pull request closed without merging**
