### PR TITLE
av1an: fix compilation

### LINKED ISSUE #2806: mingw64 Av1an build failed
09:13:12 ┌ Av1an git  ................................ [Recently updated]
09:13:16 ├ Running rust.update...
09:13:24 ├ Running rust.build...
Likely error (tail of the failed operation logfile):
help: consider importing one of these unit variants
   |
1  + use crate::software::scaling::SwsFlags::SWS_ERROR_DIFFUSION;
   |
1  + use ffmpeg_sys_the_third::SwsFlags::SWS_ERROR_DIFFUSION;
   |

For more information about this error, try `rustc --explain E0425`.
error: could not compile `ffmpeg-the-third` (lib) due to 18 previous errors
warning: build failed, waiting for other jobs to finish...

[logs.zip](https://github.com/user-attachments/files/17988376/logs.zip)

### PR DESCRIPTION
**Pull request by woot000**
Fixes #2806

### CODE REVIEW

**Comment by igorbaryshev** [comment]
perfect 
image

**Comment by L4cache** [comment]
What if there's already a `#xxx` specified in ffmpegPath?

**Comment by 1480c1** [comment]
> What if there's already a `#xxx` specified in ffmpegPath?

Unfortunately, the logic would result in
```bash
$ vcsURL="https://gitlab.com/FFmpeg/FFmpeg.git#branch=fff#tag=5555"
$ echo "${vcsURL#*#}"
branch=fff#tag=5555
```

**Comment by 1480c1** [comment]
For now, I will merge, and add a change to make it strip pre-existing revision stuff since it shouldn't care in this case.

**Pull request merged**
