### PR TITLE
Github: Add github actions

### PR DESCRIPTION
**Pull request by 1480c1**
Runs in about 2h 15m

https://github.com/1480c1/media-autobuild_suite/commit/ea9f48a1fa86e2e64c9f247514155cadf3168256/checks

### CODE REVIEW

**Comment by 1480c1** [comment]
Requires that the artifactory api key to be set, but I don't have access to the secrets setttings

**Comment by 1480c1** [comment]
Closing until I can find a way to keep the ccache between builds without needing to use artifactory api keys

**Comment by wiiaboo** [comment]
Are you sure you don't have access to Secrets? I think I have the same membership as you and I seem the tab in Options.

**Comment by 1480c1** [comment]
I don't have access to the settings tab, the far-most right tab I have is insights

**Comment by wiiaboo** [comment]
How about now?

**Comment by 1480c1** [comment]
Nope

**Comment by wiiaboo** [comment]
Has to be @jb-alvarado then.

**Comment by jb-alvarado** [comment]
I think I give all rights to @wiiaboo, this is a team project, I don't think I have any rights higher then you.

What exactly is the problem, and what do you need me to do? I have no idea about actions...

**Comment by 1480c1** [comment]
I think once, it's fully ready, I'll just email the key to @wiiaboo to add to github actions.

I possibly might be able to just use a separate repo to just keep the cache files since it's around 70 MB right now

**Comment by wiiaboo** [comment]
> I think once, it's fully ready, I'll just email the key to @wiiaboo to add to github actions.
Sure.

**Comment by wiiaboo** [comment]
According to https://help.github.com/en/articles/virtual-environments-for-github-actions#creating-and-using-secrets-encrypted-variables you should only need Write permissions in the repo to access the Secrets section, which you do have. Are you sure you can't see https://github.com/m-ab-s/media-autobuild_suite/settings/secrets?

**Comment by 1480c1** [comment]
Gives a 404 for me

**Comment by 1480c1** [comment]
Wait, I can access the settings page now, but I only see options and interaction limits

**Comment by jb-alvarado** [comment]
At the moment @1480c1 have maintaining rights and that is marked as beta feature. If you want I can change it to admin.

**Comment by 1480c1** [comment]
> At the moment @1480c1 have maintaining rights and that is marked as beta feature. If you want I can change it to admin.

@jb-alvarado, can you change my right to admin at least just for this repo? I'm trying to look into adding self-hosted runners to github actions, but I'm not able to access the page necessary for it https://help.github.com/en/actions/automating-your-workflow-with-github-actions/adding-self-hosted-runners

Because it's either that or doing external CI with gitlab-runners and using self-hosted ones, but it seems a bit unnecessary to go through multiple hoops for this

**Comment by jb-alvarado** [comment]
Ok is done.

**Comment by 1480c1** [comment]
> Ok is done.

Thank you

**Pull request closed without merging**
